### ISSUE TITLE
Creating compressed files but serving uncompressed files?

### ISSUE THREAD

**Issue by systemlevel** [ovhemert/gatsby-plugin-zopfli#7] opened 2019-03-26 14:25 UTC
Great plugin.  I noticed that I'm getting compressed files generated however when I do a` gatsby  build` and a `gatsby serve` on the production build I notice that the normal uncompressed files are being served with gatsby serve.  Perhaps, I'm misunderstanding how these files are being used?

CSS files being served:

<img width="414" alt="Screen Shot 2019-03-26 at 10 21 39 AM" src="https://user-images.githubusercontent.com/894983/55004848-57a8d980-4fb1-11e9-8039-97bec63d09e5.png">

If this was serving compressed format would this not be .css.gz?

Thank you.

**Comment by ovhemert** [comment] 2019-03-26 15:27
The plugin generates the compressed output when you run gatsby build. But to see the result, you need a production webserver (for example nginx) with the correct configuration. It needs to know to serve the .gz files when they exist, and the client can handle them. This is currently not supported by the built-in Gatsby development server.

BTW: Tricking the development server in serving the .gz files would not be right, since the pre-compressed js-files are also not production-ready. They are larger, and running the compression each time you change your code (and restart compiling your changes using live-reload) would take time and slow down development.

This is actually duplicate of issue #4 .
I'll make sure it's more clearly described in the documentation to clarify.

**Comment by systemlevel** [comment] 2019-03-26 15:42
@ovhemert thanks so much for clarifying that.

**Comment by ovhemert** [comment] 2019-03-28 12:16
Added requirements section to readme that explains usage only on supported production webservers.

**Closed as completed by ovhemert** 2019-03-28 12:16 UTC
Labels: duplicate
